apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medal-bot-ingress
  namespace: medal-bot-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  tls:
    - hosts:
        - ikuro.dev
      secretName: medal-bot-tls
  rules:
    - host: ikuro.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: twitch-proxy
                port:
                  number: 80
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: medal-bot-prod-twitch-proxy@kubernetescrd
          - path: /medallas
            pathType: Prefix
            backend:
              service:
                name: medal-bot-service
                port:
                  number: 80
