apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ikuro-prod-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/redirect-permanent: 'true'
    traefik.ingress.kubernetes.io/redirect-target: 'https://twitch.tv/ikurotime'
spec:
  rules:
    - host: ikuro.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: noop-service
                port:
                  number: 80

    - host: ikuro.dev
      http:
        paths:
          - path: /medallas
            pathType: Prefix
            backend:
              service:
                name: medal-bot-prod-service
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: noop-service
  namespace: default
spec:
  type: ExternalName
  externalName: example.com
