apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medal-bot-ingress
  namespace: medal-bot-prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
    traefik.ingress.kubernetes.io/router.middlewares: twitch-proxy@kubernetescrd
spec:
  tls:
    - hosts:
        - ikuro.dev
      secretName: medal-bot-tls
  rules:
    - host: ikuro.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: twitch-proxy
                port:
                  number: 80
