resources:
  - ../../base

images:
  - name: ghcr.io/ikurotime/medal-bot
    newTag: latest

namespace: medal-bot-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: deployment-prod.yaml
  - path: ingress-prod.yaml
