resources:
  - ../../base
  - middleware-prod.yaml
images:
  - name: ghcr.io/ikurotime/medal-bot
    newTag: latest

namespace: medal-bot-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - target:
      kind: Deployment
      name: medal-bot
    path: deployment-prod.yaml
  - target:
      kind: Ingress
      name: medal-bot-ingress
    path: ingress-prod.yaml
